
variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

container:
  image: docker:stable
  only:
    - master
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest

