title = "stevey.io"

baseURL = "http://stevey.io"
languageCode = "en-us"
theme = "sidemin"
copyright = "(c) 2017 Sick Yoon"
paginate = 6


[author]
  name = "Sick Yoon"
  email = "sick.yoon@gmail.com"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Gopher"
  sidebar = false
