version: '3'

services:

  traefik:
    image: traefik
    command: --docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./acme:/etc/traefik/acme"
    container_name: traefik

  blog:
    image: registry.gitlab.com/shicky/steveyio:latest
    environment:
      - "HUGO_BASE_URL=https://stevey.io"
    labels:
      - "traefik.frontend.rule=Host:stevey.io"
    container_name: blog


