# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Sidemin"
license = "MIT"
licenselink = "https://github.com/sickyoon/steveyio"
description = ""
homepage = "https://stevey.io"
tags = []
features = []
min_version = "0.20.7"

[author]
  name = "Sick Yoon"
  homepage = "https://stevey.io"
